### PR TITLE
Remove linkerd version

### PR DESCRIPTION
**Pull request by stephanlindauer**
It's not used so lets get rid of it

### CODE REVIEW

**Comment by wmorgan** [comment]
😿 sorry to hear it!

**Comment by stephanlindauer** [comment]
@wmorgan this is just about not using the `--linkerd-version` flag anymore. :wink:

**Comment by wmorgan** [comment]
@stephanlindauer Oh that's great. Phew!

**Comment by wmorgan** [comment]
BTW we just kicked off an official ADOPTERS.md. If you're using Linkerd, would love to have you add yourselves to it!

https://github.com/linkerd/linkerd2/blob/master/ADOPTERS.md

**Pull request merged**
