### PR TITLE
Simplify errors

### PR DESCRIPTION
**Pull request by svenwltr**
Simplifying the code by crashing as soon as it is clear that the application will fail. Not entirely sure if this is a good idea. What do you think?

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/prp-kubernetes-deployment Please review.

**Comment by stephanlindauer** [comment]
> Not entirely sure if this is a good idea. 

why not?

**Comment by svenwltr** [comment]
@stephanlindauer I am just not sure if this makes the application more or less stable. In total it should [get more stable](https://en.wikipedia.org/wiki/Offensive_programming). Also we never did it this way before. If we now start with it we probably want to implement this in all CLI applications.

**Comment by svenwltr** [comment]
The only reason to do this is simplify [`apply.go`](https://github.com/rebuy-de/kubernetes-deployment/blob/080c4d72f6851bbe303a6c663016cfce61c21bd8/pkg/api/apply.go), because this is sort of the main routing and should be sort of easy to read.

**Comment by bjoernhaeuser** [comment]
but the current changes to `apply.go` are rather small?

**Comment by svenwltr** [comment]
hmm

**Pull request closed without merging**
