### PR TITLE
kubernetes-deployment as a service

### PR DESCRIPTION
**Pull request by svenwltr**
This is a first prototype for making `kubernetes-deployment` a server. It currently implements an `apply` and a `render` endpoint. The code is still a bit crappy, but I would like enhance this iteratively.

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/prp-kubernetes-deployment Please review.

**Comment by svenwltr** [comment]
Forget the review. Apply does not work, yet.

**Comment by svenwltr** [comment]
Ok, I removed the `apply` endpoint, because I think it needs to be more sophisticated. I still would like to deploy this with the `render` endpoint as a first step.

Please review.

**Comment by stephanlindauer** [comment]
what advantage do you see regarding running `kubernetes-deployment` as a server over running it locally or attached to hubot?

**Comment by svenwltr** [comment]
> what advantage do you see regarding running kubernetes-deployment as a server over running it locally or attached to hubot?

* We do not need to configure `kubernetes-deployment` locally. So instead everyone needs to configure `kubernetes-deployment` locally for every staging cluster, we just need to do it once per cluster.
* We can have endpoints like `/render` where we see the rendered result. This is very helpful for verifying that Jsonnet templates work as expected.

**Pull request merged**
